name = "Otherworld"
version = "v8 HF2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d289e99239f1b423fd3674eb07f509fb11415fc33163d871b77bcee8b1e7eff7"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
