#OLD - old circle visuals
#NEON - new circle visuals, glowing and transparent
#Allowed Values: OLD, NEON
circlesStyle = "NEON"
#
#Parameters for hand positioned circles for client casting:
#Positive is left direction from client cross
#Range: -3.4028234663852886E38 ~ 3.4028234663852886E38
xOffsetFromCross = -0.22
#Positive is up direction from client cross
#Range: -3.4028234663852886E38 ~ 3.4028234663852886E38
yOffsetFromCross = -0.2
#Positive is forwards direction from client screen
#Range: -3.4028234663852886E38 ~ 3.4028234663852886E38
zOffsetFromCross = 1.5
#
#Parameters for hand positioned circles for other entities casting
#Positive is left direction when looking from entity view direction
#Range: -3.4028234663852886E38 ~ 3.4028234663852886E38
xOffsetFromView = -0.22
#Positive is up direction when looking from entity view direction
#Range: -3.4028234663852886E38 ~ 3.4028234663852886E38
yOffsetFromView = -0.2
#Positive is forwards direction when looking from entity view direction
#Range: -3.4028234663852886E38 ~ 3.4028234663852886E38
zOffsetFromView = 1.3
#
#Parameters for under entity circles for client casting:
#Positive is upwards
#Range: -3.4028234663852886E38 ~ 3.4028234663852886E38
yOffsetFromPlayerBottom = 0.01
#
#Parameters for under entity circles for other entities casting:
#Positive is upwards
#Range: -3.4028234663852886E38 ~ 3.4028234663852886E38
yOffsetFromEntityBottom = 0.01

